import os
import sys
import json
import traceback
import datetime
import threading
import subprocess
import shutil
import tempfile
import glob


def configure_tk_runtime():
    base_prefix = getattr(sys, "base_prefix", "")
    tcl_dir = os.path.join(base_prefix, "tcl", "tcl8.6")
    tk_dir = os.path.join(base_prefix, "tcl", "tk8.6")
    if os.path.isdir(tcl_dir) and "TCL_LIBRARY" not in os.environ:
        os.environ["TCL_LIBRARY"] = tcl_dir
    if os.path.isdir(tk_dir) and "TK_LIBRARY" not in os.environ:
        os.environ["TK_LIBRARY"] = tk_dir


configure_tk_runtime()

import tkinter as tk
from tkinter import scrolledtext
from tkinter import ttk
from tkinter import messagebox, simpledialog

import deep_series
import main


BG_COLOR = "#F5F5F7"
CARD_COLOR = "#FFFFFF"
PANEL_COLOR = "#FAFAFC"
TEXT_COLOR = "#1D1D1F"
SUBTEXT_COLOR = "#6E6E73"
PRIMARY_COLOR = "#007AFF"
SUCCESS_COLOR = "#34C759"
BORDER_COLOR = "#DADAE0"
SOFT_BLUE = "#EAF3FF"
BUTTON_DISABLED = "#B9C7D8"
LOG_BG = "#FBFBFD"
BILIBILI_DESC = (
    "OpenNewsBrief daily AI and technology news brief. "
    "Generated by the OpenNewsBrief Python workflow. "
    "Project: https://github.com/maqi88933-stack/OpenNewsBrief"
)
BILIBILI_TAGS = "AI,technology,news"
DEEP_BILIBILI_TAGS = "AI,technology,deep video"
BILIBILI_TID = "171"


class NewsBriefApp:
    def __init__(self, root):
        self.root = root
        self.root.title("OpenNewsBrief")
        self.root.geometry("1220x800")
        self.root.minsize(1080, 1024)
        self.root.configure(bg=BG_COLOR)
        self.root.option_add("*Font", ("Microsoft YaHei UI", 10))

        self.topic_vars = []
        self.log_widgets = []
        self.deep_config = deep_series.load_config()
        self.latest_result = {}
        self.is_running = False
        self.is_publishing = False
        self.worker_python = self.resolve_worker_python()
        self.worker_script = os.path.join(main.ROOT_DIR, "ui_worker.py")
        self.biliup_command = self.resolve_biliup_command()

        self.status_var = tk.StringVar(value="就绪")
        self.brief_var = tk.StringVar(value="未生成")
        self.audio_var = tk.StringVar(value="未生成")
        self.video_var = tk.StringVar(value="未生成")
        self.deep_series_title_var = tk.StringVar()
        self.deep_series_desc_var = tk.StringVar()
        self.deep_episode_title_var = tk.StringVar()
        self.deep_episode_question_var = tk.StringVar()

        self.build_layout()

    def build_layout(self):
        header = tk.Frame(self.root, bg=BG_COLOR)
        header.pack(fill="x", padx=34, pady=(26, 18))

 

        body = tk.Frame(self.root, bg=BG_COLOR)
        body.pack(fill="both", expand=True, padx=34, pady=(0, 30))

        style = ttk.Style()
        style.configure("TNotebook", background=BG_COLOR, borderwidth=0)
        style.configure("TNotebook.Tab", padding=(18, 10), font=("Microsoft YaHei UI", 10, "bold"))

        notebook = ttk.Notebook(body)
        notebook.pack(fill="both", expand=True)

        daily_tab = tk.Frame(notebook, bg=BG_COLOR)
        deep_tab = tk.Frame(notebook, bg=BG_COLOR)
        notebook.add(daily_tab, text="每日简报")
        notebook.add(deep_tab, text="深度系列")

        self.build_daily_tab(daily_tab)
        self.build_deep_tab(deep_tab)

    def build_daily_tab(self, parent):
        left = tk.Frame(parent, bg=BG_COLOR)
        left.pack(side="left", fill="y", padx=(0, 22), pady=18)
        left.configure(width=360)
        left.pack_propagate(False)
        right = tk.Frame(parent, bg=BG_COLOR)
        right.pack(side="left", fill="both", expand=True, pady=18)
        self.build_control_card(left)
        self.build_result_card(left)
        self.build_log_card(right)

    def build_deep_tab(self, parent):
        left = tk.Frame(parent, bg=BG_COLOR)
        left.pack(side="left", fill="y", padx=(0, 22), pady=18)
        right = tk.Frame(parent, bg=BG_COLOR)
        right.pack(side="left", fill="both", expand=True, pady=18)
        self.build_deep_card(left)
        self.build_deep_publish_card(left)
        self.build_result_card(left)
        self.build_log_card(right)

    def build_control_card(self, parent):
        card = self.create_card(parent)
        card.pack(fill="x")

        inner = tk.Frame(card, bg=CARD_COLOR)
        inner.pack(fill="both", expand=True, padx=22, pady=22)

        tk.Label(
            inner,
            text="主题选择",
            font=("Microsoft YaHei UI", 16, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(anchor="w")

        tk.Label(
            inner,
            text="默认会执行选中的主题，并自动生成音频和视频。",
            font=("Microsoft YaHei UI", 10),
            bg=CARD_COLOR,
            fg=SUBTEXT_COLOR,
        ).pack(anchor="w", pady=(8, 16))

        for topic in main.TOPICS:
            var = tk.BooleanVar(value=True)
            self.topic_vars.append((topic, var))
            row = tk.Frame(inner, bg=PANEL_COLOR, highlightthickness=1, highlightbackground="#EEEEF2")
            row.pack(fill="x", pady=5)
            tk.Checkbutton(
                row,
                text=topic["title"],
                variable=var,
                bg=PANEL_COLOR,
                fg=TEXT_COLOR,
                activebackground=PANEL_COLOR,
                activeforeground=TEXT_COLOR,
                selectcolor=PANEL_COLOR,
                font=("Microsoft YaHei UI", 11),
                anchor="w",
                relief="flat",
                padx=10,
                pady=8,
            ).pack(anchor="w", fill="x")

        button_row = tk.Frame(inner, bg=CARD_COLOR)
        button_row.pack(fill="x", pady=(18, 0))

        self.run_button = tk.Button(
            button_row,
            text="执行选中主题",
            command=self.start_run,
            bg=PRIMARY_COLOR,
            fg="white",
            activebackground="#0067D8",
            activeforeground="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 11, "bold"),
            padx=20,
            pady=12,
            cursor="hand2",
        )
        self.run_button.pack(fill="x")

        tk.Button(
            inner,
            text="打开最新输出目录",
            command=self.open_latest_dir,
            bg=SOFT_BLUE,
            fg=PRIMARY_COLOR,
            activebackground="#DDEEFF",
            activeforeground=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 10, "bold"),
            padx=16,
            pady=10,
            cursor="hand2",
        ).pack(fill="x", pady=(12, 0))

        self.publish_button = tk.Button(
            inner,
            text="一键发布到B站",
            command=self.start_publish_to_bilibili,
            bg=SUCCESS_COLOR,
            fg="white",
            activebackground="#28A745",
            activeforeground="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 10, "bold"),
            padx=16,
            pady=10,
            cursor="hand2",
        )
        self.publish_button.pack(fill="x", pady=(12, 0))

        tk.Label(
            inner,
            textvariable=self.status_var,
            font=("Microsoft YaHei UI", 10),
            bg=CARD_COLOR,
            fg=SUCCESS_COLOR,
        ).pack(anchor="w", pady=(14, 0))

    def build_deep_card(self, parent):
        card = self.create_card(parent)
        card.pack(fill="x", pady=(20, 0))

        inner = tk.Frame(card, bg=CARD_COLOR)
        inner.pack(fill="both", expand=True, padx=22, pady=22)

        tk.Label(
            inner,
            text="深度系列",
            font=("Microsoft YaHei UI", 16, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(anchor="w")
        tk.Label(
            inner,
            text="维护系列和主题，调研写稿完成后再人工确认生成视频。",
            font=("Microsoft YaHei UI", 10),
            bg=CARD_COLOR,
            fg=SUBTEXT_COLOR,
        ).pack(anchor="w", pady=(8, 12))

        list_row = tk.Frame(inner, bg=CARD_COLOR)
        list_row.pack(fill="x")
        self.deep_series_list = tk.Listbox(
            list_row,
            height=4,
            exportselection=False,
            bg=PANEL_COLOR,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            font=("Microsoft YaHei UI", 10),
        )
        self.deep_series_list.pack(side="left", fill="both", expand=True)
        self.deep_series_list.bind("<<ListboxSelect>>", self.on_deep_series_select)

        self.deep_episode_list = tk.Listbox(
            list_row,
            height=4,
            exportselection=False,
            bg=PANEL_COLOR,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            font=("Microsoft YaHei UI", 10),
        )
        self.deep_episode_list.pack(side="left", fill="both", expand=True, padx=(10, 0))
        self.deep_episode_list.bind("<<ListboxSelect>>", self.on_deep_episode_select)

        btn_row = tk.Frame(inner, bg=CARD_COLOR)
        btn_row.pack(fill="x", pady=(12, 0))
        tk.Button(
            btn_row,
            text="编辑系列",
            command=self.edit_deep_series_popup,
            bg=CARD_COLOR,
            fg=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True)
        tk.Button(
            btn_row,
            text="新增系列",
            command=self.new_deep_series_popup,
            bg=SOFT_BLUE,
            fg=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True, padx=(8, 0))
        tk.Button(
            btn_row,
            text="删除系列",
            command=self.delete_deep_series,
            bg="#FFECEC",
            fg="#D70015",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True, padx=(8, 0))

        episode_btn_row = tk.Frame(inner, bg=CARD_COLOR)
        episode_btn_row.pack(fill="x", pady=(8, 0))
        tk.Button(
            episode_btn_row,
            text="编辑主题",
            command=self.edit_deep_episode_popup,
            bg=CARD_COLOR,
            fg=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True)
        tk.Button(
            episode_btn_row,
            text="新增主题",
            command=self.new_deep_episode_popup,
            bg=SOFT_BLUE,
            fg=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True, padx=(8, 0))
        tk.Button(
            episode_btn_row,
            text="删除主题",
            command=self.delete_deep_episode,
            bg="#FFECEC",
            fg="#D70015",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True, padx=(8, 0))

        self.deep_run_button = tk.Button(
            inner,
            text="调研并写稿",
            command=self.start_deep_run,
            bg="#111111",
            fg="white",
            activebackground="#333333",
            activeforeground="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 10, "bold"),
            padx=16,
            pady=10,
            cursor="hand2",
        )
        self.deep_run_button.pack(fill="x", pady=(12, 0))
        self.deep_run_series_button = tk.Button(
            inner,
            text="生成整组稿件",
            command=self.start_deep_series_run,
            bg="#2C2C2E",
            fg="white",
            activebackground="#3A3A3C",
            activeforeground="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 10, "bold"),
            padx=16,
            pady=10,
            cursor="hand2",
        )
        self.deep_run_series_button.pack(fill="x", pady=(10, 0))
        self.deep_generate_video_button = tk.Button(
            inner,
            text="审核后生成视频",
            command=self.start_deep_generate_video,
            bg=PRIMARY_COLOR,
            fg="white",
            activebackground="#0067D8",
            activeforeground="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 10, "bold"),
            padx=16,
            pady=10,
            cursor="hand2",
        )
        self.deep_generate_video_button.pack(fill="x", pady=(10, 0))
        self.refresh_deep_lists()

    def build_entry(self, parent, label, text_var):
        row = tk.Frame(parent, bg=CARD_COLOR)
        row.pack(fill="x", pady=(10, 0))
        tk.Label(
            row,
            text=label,
            width=5,
            anchor="w",
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
            font=("Microsoft YaHei UI", 9, "bold"),
        ).pack(side="left")
        tk.Entry(
            row,
            textvariable=text_var,
            bg=PANEL_COLOR,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            font=("Microsoft YaHei UI", 10),
        ).pack(side="left", fill="x", expand=True)

    def build_deep_publish_card(self, parent):
        card = self.create_card(parent)
        card.pack(fill="x", pady=(20, 0))

        inner = tk.Frame(card, bg=CARD_COLOR)
        inner.pack(fill="both", expand=True, padx=22, pady=22)

        tk.Label(
            inner,
            text="深度视频发布",
            font=("Microsoft YaHei UI", 16, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(anchor="w")
        tk.Label(
            inner,
            text="选择已生成的视频后发布，发布信息会优先使用深度系列元数据。",
            font=("Microsoft YaHei UI", 10),
            bg=CARD_COLOR,
            fg=SUBTEXT_COLOR,
        ).pack(anchor="w", pady=(8, 12))

        self.deep_publish_tab = "pending"
        self.deep_publish_notebook = ttk.Notebook(inner)
        self.deep_publish_notebook.pack(fill="x")

        pending_frame = tk.Frame(self.deep_publish_notebook, bg=CARD_COLOR)
        published_frame = tk.Frame(self.deep_publish_notebook, bg=CARD_COLOR)
        self.deep_publish_notebook.add(pending_frame, text="待发布")
        self.deep_publish_notebook.add(published_frame, text="已发布")
        self.deep_publish_notebook.bind("<<NotebookTabChanged>>", self.on_deep_publish_tab_changed)

        self.deep_pending_publish_list = tk.Listbox(
            pending_frame,
            height=5,
            exportselection=False,
            bg=PANEL_COLOR,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            font=("Microsoft YaHei UI", 10),
        )
        self.deep_pending_publish_list.pack(fill="x")
        self.deep_published_list = tk.Listbox(
            published_frame,
            height=5,
            exportselection=False,
            bg=PANEL_COLOR,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            font=("Microsoft YaHei UI", 10),
        )
        self.deep_published_list.pack(fill="x")
        self.deep_publish_list = self.deep_pending_publish_list

        btn_row = tk.Frame(inner, bg=CARD_COLOR)
        btn_row.pack(fill="x", pady=(12, 0))
        tk.Button(
            btn_row,
            text="刷新",
            command=self.refresh_deep_publish_list,
            bg=SOFT_BLUE,
            fg=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        ).pack(side="left", fill="x", expand=True)
        self.deep_publish_selected_button = tk.Button(
            btn_row,
            text="发布选中",
            command=self.start_publish_selected_deep_video,
            bg=SUCCESS_COLOR,
            fg="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=10,
            pady=8,
            cursor="hand2",
        )
        self.deep_publish_selected_button.pack(side="left", fill="x", expand=True, padx=(8, 0))
        self.deep_publish_all_button = tk.Button(
            inner,
            text="发布全部",
            command=self.start_publish_deep_series_videos,
            bg=SUCCESS_COLOR,
            fg="white",
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 10, "bold"),
            padx=16,
            pady=10,
            cursor="hand2",
        )
        self.deep_publish_all_button.pack(fill="x", pady=(10, 0))
        self.update_deep_publish_buttons()
        self.refresh_deep_publish_list()

    def build_result_card(self, parent):
        card = self.create_card(parent)
        card.pack(fill="x", pady=(20, 0))

        inner = tk.Frame(card, bg=CARD_COLOR)
        inner.pack(fill="both", expand=True, padx=22, pady=22)

        tk.Label(
            inner,
            text="最新结果",
            font=("Microsoft YaHei UI", 16, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(anchor="w")

        self.build_path_row(inner, "简报", self.brief_var, "brief_path")
        self.build_path_row(inner, "音频", self.audio_var, "audio_path")
        self.build_path_row(inner, "视频", self.video_var, "video_path")

    def build_path_row(self, parent, label, text_var, field_name):
        row = tk.Frame(parent, bg=CARD_COLOR)
        row.pack(fill="x", pady=(14, 0))

        tk.Label(
            row,
            text=label,
            width=6,
            anchor="w",
            font=("Microsoft YaHei UI", 10, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(side="left")

        tk.Entry(
            row,
            textvariable=text_var,
            font=("Microsoft YaHei UI", 9),
            bg=PANEL_COLOR,
            fg=SUBTEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            readonlybackground=PANEL_COLOR,
            state="readonly",
        ).pack(side="left", fill="x", expand=True, padx=(0, 8), ipady=5)

        tk.Button(
            row,
            text="打开",
            command=lambda key=field_name: self.open_result_file(key),
            bg=CARD_COLOR,
            fg=PRIMARY_COLOR,
            activebackground=CARD_COLOR,
            activeforeground=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            cursor="hand2",
        ).pack(side="right")

    def build_log_card(self, parent):
        card = self.create_card(parent)
        card.pack(fill="both", expand=True)

        inner = tk.Frame(card, bg=CARD_COLOR)
        inner.pack(fill="both", expand=True, padx=22, pady=22)

        top_row = tk.Frame(inner, bg=CARD_COLOR)
        top_row.pack(fill="x")

        tk.Label(
            top_row,
            text="运行日志",
            font=("Microsoft YaHei UI", 16, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(side="left")

        tk.Button(
            top_row,
            text="清空",
            command=self.clear_log,
            bg=CARD_COLOR,
            fg=PRIMARY_COLOR,
            activebackground=CARD_COLOR,
            activeforeground=PRIMARY_COLOR,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            cursor="hand2",
        ).pack(side="right")

        self.log_widget = scrolledtext.ScrolledText(
            inner,
            bg=LOG_BG,
            fg=TEXT_COLOR,
            insertbackground=TEXT_COLOR,
            relief="flat",
            borderwidth=0,
            highlightthickness=1,
            highlightbackground="#EEEEF2",
            highlightcolor="#C7D2FE",
            font=("Cascadia Mono", 10),
            wrap="word",
            padx=14,
            pady=14,
        )
        self.log_widget.pack(fill="both", expand=True, pady=(14, 0))
        self.log_widgets.append(self.log_widget)

    def create_card(self, parent):
        return tk.Frame(
            parent,
            bg=CARD_COLOR,
            bd=0,
            relief="flat",
            highlightthickness=1,
            highlightbackground=BORDER_COLOR,
            highlightcolor=BORDER_COLOR,
        )

    def refresh_deep_lists(self):
        self.deep_series_list.delete(0, "end")
        for series in self.deep_config.get("series", []):
            self.deep_series_list.insert("end", series.get("title", "未命名系列"))
        if self.deep_config.get("series"):
            self.deep_series_list.selection_set(0)
            self.on_deep_series_select()

    def get_selected_deep_series_index(self):
        selection = self.deep_series_list.curselection()
        return selection[0] if selection else -1

    def get_selected_deep_episode_index(self):
        selection = self.deep_episode_list.curselection()
        return selection[0] if selection else -1

    def on_deep_series_select(self, _event=None):
        index = self.get_selected_deep_series_index()
        if index < 0:
            return
        series = self.deep_config.get("series", [])[index]
        self.deep_series_title_var.set(series.get("title", ""))
        self.deep_series_desc_var.set(series.get("description", ""))

        self.deep_episode_list.delete(0, "end")
        for episode in series.get("episodes", []):
            if episode.get("generated") and episode.get("video_path"):
                status = "已生成"
            elif episode.get("review_ready") and episode.get("script_path"):
                status = "待生成视频"
            else:
                status = "未生成"
            self.deep_episode_list.insert("end", f"[{status}] {episode.get('title', '未命名主题')}")
        if series.get("episodes"):
            self.deep_episode_list.selection_set(0)
            self.on_deep_episode_select()
        else:
            self.deep_episode_title_var.set("")
            self.deep_episode_question_var.set("")

    def on_deep_episode_select(self, _event=None):
        series_index = self.get_selected_deep_series_index()
        episode_index = self.get_selected_deep_episode_index()
        if series_index < 0 or episode_index < 0:
            return
        episode = self.deep_config["series"][series_index].get("episodes", [])[episode_index]
        self.deep_episode_title_var.set(episode.get("title", ""))
        self.deep_episode_question_var.set(episode.get("question", ""))
        self.refresh_deep_publish_list()

    def new_deep_series(self):
        self.deep_series_list.selection_clear(0, "end")
        self.deep_episode_list.delete(0, "end")
        self.deep_series_title_var.set("")
        self.deep_series_desc_var.set("")
        self.deep_episode_title_var.set("")
        self.deep_episode_question_var.set("")

    def get_generated_deep_episodes(self, series=None):
        return self.get_deep_publish_episodes(series=series, tab_name="pending")

    def get_deep_publish_episodes(self, series=None, tab_name="pending"):
        target_series = series
        if target_series is None:
            series_index = self.get_selected_deep_series_index()
            if series_index < 0:
                return []
            target_series = self.deep_config["series"][series_index]
        items = []
        for episode in target_series.get("episodes", []):
            video_path = episode.get("video_path", "")
            if not (episode.get("generated") and video_path and os.path.exists(video_path)):
                continue
            is_published = bool(episode.get("published"))
            if tab_name == "published":
                if is_published:
                    items.append((target_series, episode))
            elif not is_published:
                items.append((target_series, episode))
        return items

    def on_deep_publish_tab_changed(self, _event=None):
        if not hasattr(self, "deep_publish_notebook"):
            return
        current_tab = self.deep_publish_notebook.tab(self.deep_publish_notebook.select(), "text")
        self.deep_publish_tab = "published" if current_tab == "已发布" else "pending"
        self.deep_publish_list = self.deep_published_list if self.deep_publish_tab == "published" else self.deep_pending_publish_list
        self.update_deep_publish_buttons()

    def update_deep_publish_buttons(self):
        if not hasattr(self, "deep_publish_selected_button"):
            return
        if getattr(self, "deep_publish_tab", "pending") == "published":
            self.deep_publish_selected_button.config(state="disabled", bg=BUTTON_DISABLED)
            self.deep_publish_all_button.config(state="disabled", bg=BUTTON_DISABLED)
        else:
            self.deep_publish_selected_button.config(state="normal", bg=SUCCESS_COLOR)
            self.deep_publish_all_button.config(state="normal", bg=SUCCESS_COLOR)

    def refresh_deep_publish_list(self):
        if not hasattr(self, "deep_pending_publish_list"):
            return
        self.deep_pending_publish_list.delete(0, "end")
        self.deep_published_list.delete(0, "end")
        for _series, episode in self.get_deep_publish_episodes(tab_name="pending"):
            self.deep_pending_publish_list.insert("end", episode.get("title", "未命名主题"))
        for _series, episode in self.get_deep_publish_episodes(tab_name="published"):
            self.deep_published_list.insert("end", episode.get("title", "未命名主题"))
        self.on_deep_publish_tab_changed()

    def get_selected_topics(self):
        return [topic for topic, var in self.topic_vars if var.get()]

    def start_run(self):
        if self.is_running:
            return

        topics = self.get_selected_topics()
        if not topics:
            self.append_log("请先选择至少一个主题。\n")
            return

        self.is_running = True
        self.run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_generate_video_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.publish_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.status_var.set("正在生成每日简报...")
        worker = threading.Thread(target=self.run_topics, args=(topics,), daemon=True)
        worker.start()

    def start_deep_run(self):
        if self.is_running:
            return
        series, episode = self.get_selected_deep_target()
        if not series or not episode:
            self.append_log("请先选择一个深度系列和主题。\n")
            return

        self.is_running = True
        self.run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_generate_video_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.publish_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.status_var.set("正在调研和写稿...")
        worker = threading.Thread(target=self.run_deep_episode, args=(series["title"], episode["title"]), daemon=True)
        worker.start()

    def start_deep_series_run(self):
        if self.is_running:
            return
        series_index = self.get_selected_deep_series_index()
        if series_index < 0:
            self.append_log("请先选择一个深度系列。\n")
            return
        series = self.deep_config["series"][series_index]
        if not series.get("episodes"):
            self.append_log("当前系列没有主题。\n")
            return

        self.is_running = True
        self.run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_series_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_generate_video_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.publish_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.status_var.set("正在生成整组稿件...")
        worker = threading.Thread(target=self.run_deep_series, args=(series["title"],), daemon=True)
        worker.start()

    def start_deep_generate_video(self):
        if self.is_running:
            return
        series, episode = self.get_selected_deep_target()
        if not series or not episode:
            self.append_log("请先选择一个深度系列和主题。\n")
            return
        script_path = episode.get("script_path", "")
        if not script_path or not os.path.exists(script_path):
            self.append_log("未找到脚本，请先执行调研和写稿。\n")
            return
        if not messagebox.askyesno("生成视频", "请确认已人工审核并修改脚本，是否开始生成视频？", parent=self.root):
            return

        self.is_running = True
        self.run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_series_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_generate_video_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.publish_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.status_var.set("正在生成深度视频...")
        worker = threading.Thread(
            target=self.run_deep_generate_video,
            args=(series["title"], episode["title"]),
            daemon=True,
        )
        worker.start()
    def run_topics(self, topics):
        try:
            if not os.path.exists(self.worker_python):
                self.append_log(f"找不到 Python 解释器：{self.worker_python}\n")
                return

            for topic in topics:
                self.append_log(f"\n{'=' * 56}\n")
                self.append_log(f"开始执行主题：{topic['title']}\n")
                self.append_log(f"{'=' * 56}\n")
                result = self.run_topic_subprocess(topic["title"])
                if result:
                    self.latest_result = result
                    self.update_result_panel(result)
        except Exception:
            self.append_log(traceback.format_exc())
        finally:
            self.finish_run()

    def run_deep_episode(self, series_title, episode_title):
        try:
            if not os.path.exists(self.worker_python):
                self.append_log(f"找不到 Python 解释器：{self.worker_python}\n")
                return

            self.append_log(f"\n{'=' * 56}\n")
            self.append_log(f"开始调研和写稿：{series_title} / {episode_title}\n")
            self.append_log(f"{'=' * 56}\n")
            result = self.run_worker_subprocess(["--deep", series_title, episode_title])
            if result:
                self.latest_result = result
                self.update_result_panel(result)
                self.reload_deep_config()
        except Exception:
            self.append_log(traceback.format_exc())
        finally:
            self.finish_run()

    def run_deep_series(self, series_title):
        try:
            if not os.path.exists(self.worker_python):
                self.append_log(f"找不到 Python 解释器：{self.worker_python}\n")
                return
            series = deep_series.find_series(self.deep_config, series_title)
            for episode in list(series.get("episodes", [])):
                self.append_log(f"\n{'=' * 56}\n")
                self.append_log(f"开始调研和写稿：{series_title} / {episode.get('title')}\n")
                self.append_log(f"{'=' * 56}\n")
                result = self.run_worker_subprocess(["--deep", series_title, episode.get("title", "")])
                if result:
                    self.latest_result = result
                    self.update_result_panel(result)
                    self.reload_deep_config()
        except Exception:
            self.append_log(traceback.format_exc())
        finally:
            self.finish_run()

    def run_deep_generate_video(self, series_title, episode_title):
        try:
            self.append_log(f"\n{'=' * 56}\n")
            self.append_log(f"开始生成深度视频：{series_title} / {episode_title}\n")
            self.append_log(f"{'=' * 56}\n")
            self.append_log("ChatTTS 模型将在 UI 进程内加载；本次 UI 打开期间后续生成会复用同一个模型。\n")
            result = deep_series.generate_episode_video_by_titles(series_title, episode_title)
            if result:
                self.latest_result = result
                self.update_result_panel(result)
                self.reload_deep_config()
        except Exception:
            self.append_log(traceback.format_exc())
        finally:
            self.finish_run()

    def reload_deep_config(self):
        self.deep_config = deep_series.load_config()
        self.root.after(0, self.refresh_deep_lists)
        self.root.after(0, self.refresh_deep_publish_list)

    def run_topic_subprocess(self, topic_title):
        return self.run_worker_subprocess([topic_title])

    def run_worker_subprocess(self, args):
        command = [self.worker_python, "-X", "utf8", self.worker_script] + list(args)
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUTF8"] = "1"
        process = subprocess.Popen(
            command,
            cwd=main.ROOT_DIR,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )

        result = None
        if process.stdout is not None:
            for line in process.stdout:
                if line.startswith("__RESULT__"):
                    result = json.loads(line[len("__RESULT__"):].strip())
                    continue
                self.append_log(line)

        return_code = process.wait()
        if return_code != 0:
            self.append_log(f"子进程执行失败，退出码：{return_code}\n")
        return result

    def resolve_worker_python(self):
        venv_python = os.path.join(main.ROOT_DIR, ".venv", "Scripts", "python.exe")
        if os.path.exists(venv_python):
            return venv_python
        return sys.executable

    def finish_run(self):
        def _finish():
            self.is_running = False
            self.run_button.config(state="normal", bg=PRIMARY_COLOR)
            self.deep_run_button.config(state="normal", bg="#111111")
            self.deep_run_series_button.config(state="normal", bg="#2C2C2E")
            self.deep_generate_video_button.config(state="normal", bg=PRIMARY_COLOR)
            if not self.is_publishing:
                self.publish_button.config(state="normal", bg=SUCCESS_COLOR)
            self.status_var.set(f"就绪 {datetime.datetime.now().strftime('%H:%M:%S')}")

        self.root.after(0, _finish)

    def update_result_panel(self, result):
        def _update():
            self.brief_var.set(result.get("brief_path") or result.get("script_path") or result.get("research_path") or "未生成")
            self.audio_var.set(result.get("audio_path") or "未生成")
            self.video_var.set(result.get("video_path") or "未生成")

        self.root.after(0, _update)

    def append_log(self, text):
        def _append():
            for widget in self.log_widgets:
                widget.insert("end", text)
                widget.see("end")

        self.root.after(0, _append)

    def clear_log(self):
        for widget in self.log_widgets:
            widget.delete("1.0", "end")

    def open_result_file(self, key):
        path = self.latest_result.get(key)
        if key == "brief_path" and not path:
            path = self.latest_result.get("script_path") or self.latest_result.get("research_path")
        if path and os.path.exists(path):
            os.startfile(path)

    def start_publish_to_bilibili(self):
        if self.is_running:
            self.append_log("当前正在运行，不能发布。\n")
            return
        if self.is_publishing:
            return

        video_path = self.get_publish_video_path()
        if not video_path:
            self.append_log("未找到可发布的视频。\n")
            return

        self.biliup_command = self.resolve_biliup_command()
        if not self.biliup_command:
            self.append_log("未找到 biliup 命令，无法发布到B站。\n")
            self.append_log("请先安装或登录 bbup-app。\n")
            return

        self.is_publishing = True
        self.publish_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_publish_selected_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_publish_all_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_series_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_generate_video_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.status_var.set("正在发布到B站...")
        worker = threading.Thread(target=self.publish_to_bilibili, args=(video_path,), daemon=True)
        worker.start()

    def start_publish_selected_deep_video(self):
        if self.is_running or self.is_publishing:
            return
        if getattr(self, "deep_publish_tab", "pending") == "published":
            self.append_log("已发布列表中的视频不能再次发布，请先重新生成。\n")
            return
        generated = self.get_generated_deep_episodes()
        selection = self.deep_pending_publish_list.curselection()
        if not selection or selection[0] >= len(generated):
            self.append_log("请先在待发布列表选择一个视频。\n")
            return
        series, episode = generated[selection[0]]
        result = self.build_deep_publish_result(series, episode)
        if not result.get("video_path"):
            self.append_log("选中的视频不存在，无法发布。\n")
            return
        self.latest_result = result
        self.update_result_panel(result)
        self.start_publish_to_bilibili()

    def start_publish_deep_series_videos(self):
        if self.is_running or self.is_publishing:
            return
        generated = self.get_generated_deep_episodes()
        if not generated:
            self.append_log("当前系列没有已生成的视频。\n")
            return
        self.biliup_command = self.resolve_biliup_command()
        if not self.biliup_command:
            self.append_log("未找到 biliup 命令，无法发布到B站。\n")
            return

        results = [self.build_deep_publish_result(series, episode) for series, episode in generated]
        self.is_publishing = True
        self.publish_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_publish_selected_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_publish_all_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_run_series_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.deep_generate_video_button.config(state="disabled", bg=BUTTON_DISABLED)
        self.status_var.set("正在批量发布深度视频...")
        worker = threading.Thread(target=self.publish_many_to_bilibili, args=(results,), daemon=True)
        worker.start()

    def build_deep_publish_result(self, series, episode):
        result = {
            "series": series.get("title", ""),
            "episode": episode.get("title", ""),
            "research_path": episode.get("research_path", ""),
            "audit_path": episode.get("audit_path", ""),
            "script_path": episode.get("script_path", ""),
            "audio_path": episode.get("audio_path", ""),
            "video_path": episode.get("video_path", ""),
            "publish_assets_path": episode.get("publish_assets_path", ""),
            "publish_title": episode.get("publish_title", ""),
            "publish_desc": episode.get("publish_desc", ""),
            "publish_tags": episode.get("publish_tags", ""),
            "published": bool(episode.get("published")),
        }
        assets_path = result.get("publish_assets_path")
        if assets_path and os.path.exists(assets_path):
            try:
                with open(assets_path, "r", encoding="utf-8") as f:
                    assets = json.load(f)
                result["publish_title"] = result["publish_title"] or assets.get("title", "")
                result["publish_desc"] = result["publish_desc"] or assets.get("desc", "")
                result["publish_tags"] = result["publish_tags"] or assets.get("tags", "")
            except (OSError, json.JSONDecodeError):
                pass
        if result.get("video_path") and not result.get("publish_desc"):
            try:
                assets = deep_series.generate_publish_assets(series, episode, result)
                result["publish_assets_path"] = assets.get("path", "")
                result["publish_title"] = assets.get("title", "")
                result["publish_desc"] = assets.get("desc", "")
                result["publish_tags"] = assets.get("tags", "")
                episode["publish_assets_path"] = result["publish_assets_path"]
                episode["publish_title"] = result["publish_title"]
                episode["publish_desc"] = result["publish_desc"]
                episode["publish_tags"] = result["publish_tags"]
                deep_series.save_config(self.deep_config)
            except Exception as exc:
                self.append_log(f"AI 发布信息生成失败：{exc}\n")
        return result

    def mark_deep_episode_published(self, series_title, episode_title):
        if not series_title or not episode_title:
            return
        series = deep_series.find_series(self.deep_config, series_title)
        episode = deep_series.find_episode(series, episode_title)
        episode["published"] = True
        episode["published_at"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        deep_series.save_config(self.deep_config)

    def get_publish_video_path(self):
        video_path = self.latest_result.get("video_path")
        if video_path and os.path.exists(video_path):
            return video_path
        return self.find_latest_video_file()

    def find_latest_video_file(self):
        base_dirs = [
            os.path.join(main.ROOT_DIR, "audioContent"),
            os.path.join(main.ROOT_DIR, "deepContent"),
        ]
        latest_path = ""
        latest_mtime = -1
        for base_dir in base_dirs:
            for root, _dirs, files in os.walk(base_dir, onerror=lambda _err: None):
                for filename in files:
                    if not filename.lower().endswith(".mp4"):
                        continue
                    path = os.path.join(root, filename)
                    try:
                        mtime = os.path.getmtime(path)
                    except OSError:
                        continue
                    if mtime > latest_mtime:
                        latest_path = path
                        latest_mtime = mtime
        return latest_path

    def resolve_biliup_command(self):
        command = shutil.which("biliup")
        if command:
            return command

        local_app_data = os.environ.get("LOCALAPPDATA")
        if local_app_data:
            bbup_biliup = os.path.join(local_app_data, "bbup-app", "binaries", "biliup.exe")
            if os.path.exists(bbup_biliup):
                return bbup_biliup

        return ""

    def resolve_biliup_cookie_path(self):
        env_cookie = os.environ.get("BILIUP_USER_COOKIE")
        if env_cookie and os.path.exists(env_cookie):
            return env_cookie

        project_cookie = os.path.join(main.ROOT_DIR, "cookies.json")
        if os.path.exists(project_cookie):
            return project_cookie

        local_app_data = os.environ.get("LOCALAPPDATA")
        if not local_app_data:
            return ""

        pattern = os.path.join(local_app_data, "bbup-app", "data", "*.json")
        cookie_files = glob.glob(pattern)
        if not cookie_files:
            return ""

        cookie_files.sort(key=os.path.getmtime, reverse=True)
        temp_cookie = os.path.join(tempfile.gettempdir(), "OpenNewsBrief_biliup_cookie.json")
        try:
            shutil.copyfile(cookie_files[0], temp_cookie)
        except OSError:
            return ""
        return temp_cookie

    def build_biliup_upload_command(self, video_path):
        title = os.path.splitext(os.path.basename(video_path))[0]
        desc = BILIBILI_DESC
        tags = BILIBILI_TAGS
        latest_result = getattr(self, "latest_result", {})
        if latest_result.get("series"):
            title = self.format_deep_publish_title(latest_result.get("series", ""), latest_result.get("publish_title") or title)
            desc = (
                f"{latest_result.get('series', '')} / {latest_result.get('episode', '')}\n"
                "本视频为 OpenNewsBrief 深度系列内容，基于调研、审稿和脚本生成流程制作。"
            )
            desc = latest_result.get("publish_desc") or desc
            tags = latest_result.get("publish_tags") or DEEP_BILIBILI_TAGS
        command = [self.biliup_command or "biliup"]
        cookie_path = self.resolve_biliup_cookie_path()
        if cookie_path:
            command.extend(["--user-cookie", cookie_path])
        command.extend([
            "upload",
            "--copyright",
            "1",
            "--tid",
            BILIBILI_TID,
            "--tag",
            tags,
            "--title",
            title,
            "--desc",
            desc,
            video_path,
        ])
        return command

    def format_deep_publish_title(self, series_title, title):
        series_title = (series_title or "").strip()
        title = (title or "").strip()
        if not series_title:
            return title
        prefix = f"{series_title}："
        return title if title.startswith(prefix) else prefix + title

    def publish_to_bilibili(self, video_path):
        try:
            if self.publish_video_once(video_path):
                latest_result = getattr(self, "latest_result", {})
                self.mark_deep_episode_published(latest_result.get("series", ""), latest_result.get("episode", ""))
        finally:
            self.finish_publish()

    def publish_video_once(self, video_path):
        command = self.build_biliup_upload_command(video_path)
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUTF8"] = "1"
        self.append_log(f"开始发布视频：{video_path}\n")
        try:
            process = subprocess.Popen(
                command,
                cwd=main.ROOT_DIR,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                bufsize=1,
            )
            if process.stdout is not None:
                for line in process.stdout:
                    self.append_log(line)

            return_code = process.wait()
            if return_code == 0:
                self.append_log("B站发布完成。\n")
                return True
            else:
                self.append_log(f"B站发布失败，退出码：{return_code}\n")
        except Exception:
            self.append_log(traceback.format_exc())
        return False

    def publish_many_to_bilibili(self, results):
        try:
            for result in results:
                video_path = result.get("video_path", "")
                if not video_path or not os.path.exists(video_path):
                    self.append_log(f"视频文件不存在，跳过发布：{video_path}\n")
                    continue
                self.latest_result = result
                self.update_result_panel(result)
                if self.publish_video_once(video_path):
                    self.mark_deep_episode_published(result.get("series", ""), result.get("episode", ""))
        finally:
            self.finish_publish()

    def finish_publish(self):
        def _finish():
            self.is_publishing = False
            self.publish_button.config(state="normal", bg=SUCCESS_COLOR)
            self.deep_publish_selected_button.config(state="normal", bg=SUCCESS_COLOR)
            self.deep_publish_all_button.config(state="normal", bg=SUCCESS_COLOR)
            if not self.is_running:
                self.run_button.config(state="normal", bg=PRIMARY_COLOR)
                self.deep_run_button.config(state="normal", bg="#111111")
                self.deep_run_series_button.config(state="normal", bg="#2C2C2E")
                self.deep_generate_video_button.config(state="normal", bg=PRIMARY_COLOR)
            self.status_var.set(f"发布完成 {datetime.datetime.now().strftime('%H:%M:%S')}")
            self.refresh_deep_lists()
            self.refresh_deep_publish_list()
            self.update_deep_publish_buttons()

        self.root.after(0, _finish)

    def build_daily_tab(self, parent):
        top = tk.Frame(parent, bg=BG_COLOR)
        top.pack(fill="both", expand=True, padx=0, pady=(18, 10))
        bottom = tk.Frame(parent, bg=BG_COLOR)
        bottom.pack(fill="both", expand=True, padx=0, pady=(0, 18))

        left = tk.Frame(top, bg=BG_COLOR, width=360)
        left.pack(side="left", fill="y", padx=(0, 22))
        left.pack_propagate(False)
        right = tk.Frame(top, bg=BG_COLOR)
        right.pack(side="left", fill="both", expand=True)

        self.build_control_card(left)
        self.build_result_card(right)
        self.build_log_card(bottom)

    def build_deep_tab(self, parent):
        top = tk.Frame(parent, bg=BG_COLOR)
        top.pack(fill="both", expand=True, padx=0, pady=(18, 10))
        bottom = tk.Frame(parent, bg=BG_COLOR)
        bottom.pack(fill="both", expand=True, padx=0, pady=(0, 18))

        main_area = tk.Frame(top, bg=BG_COLOR)
        main_area.pack(side="left", fill="both", expand=True, padx=(0, 22))
        side_area = tk.Frame(top, bg=BG_COLOR, width=330)
        side_area.pack(side="left", fill="y")
        side_area.pack_propagate(False)

        self.build_deep_card(main_area)
        self.build_result_card(side_area)
        self.build_deep_publish_card(side_area)
        self.build_log_card(bottom)

    def build_deep_card(self, parent):
        card = self.create_card(parent)
        card.pack(fill="both", expand=True)

        inner = tk.Frame(card, bg=CARD_COLOR)
        inner.pack(fill="both", expand=True, padx=22, pady=22)

        header = tk.Frame(inner, bg=CARD_COLOR)
        header.pack(fill="x")
        tk.Label(
            header,
            text="深度系列工作台",
            font=("Microsoft YaHei UI", 16, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(side="left")
        tk.Label(
            header,
            textvariable=self.status_var,
            font=("Microsoft YaHei UI", 10),
            bg=CARD_COLOR,
            fg=SUCCESS_COLOR,
        ).pack(side="right")

        series_section = tk.Frame(inner, bg=CARD_COLOR)
        series_section.pack(fill="x", pady=(14, 0))
        tk.Label(
            series_section,
            text="系列列表",
            font=("Microsoft YaHei UI", 11, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(anchor="w")

        series_columns = ("title", "episodes", "description")
        self.deep_series_table = ttk.Treeview(
            series_section,
            columns=series_columns,
            show="headings",
            height=4,
            selectmode="browse",
        )
        self.deep_series_table.heading("title", text="系列")
        self.deep_series_table.heading("episodes", text="主题数")
        self.deep_series_table.heading("description", text="说明")
        self.deep_series_table.column("title", width=180, anchor="w")
        self.deep_series_table.column("episodes", width=70, anchor="center")
        self.deep_series_table.column("description", width=420, anchor="w")
        self.deep_series_table.pack(fill="x", pady=(8, 0))
        self.deep_series_table.bind("<<TreeviewSelect>>", self.on_deep_series_select)

        series_actions = tk.Frame(series_section, bg=CARD_COLOR)
        series_actions.pack(fill="x", pady=(10, 0))
        self.create_action_button(series_actions, "新增系列", self.new_deep_series_popup, SOFT_BLUE, PRIMARY_COLOR)
        self.create_action_button(series_actions, "编辑系列", self.edit_deep_series_popup, CARD_COLOR, PRIMARY_COLOR)
        self.create_action_button(series_actions, "删除系列", self.delete_deep_series, "#FFECEC", "#D70015")

        episode_section = tk.Frame(inner, bg=CARD_COLOR)
        episode_section.pack(fill="both", expand=True, pady=(18, 0))
        tk.Label(
            episode_section,
            text="主题列表",
            font=("Microsoft YaHei UI", 11, "bold"),
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
        ).pack(anchor="w")

        episode_columns = ("title", "status", "question", "updated")
        table_wrap = tk.Frame(episode_section, bg=CARD_COLOR)
        table_wrap.pack(fill="both", expand=True, pady=(8, 0))
        self.deep_episode_table = ttk.Treeview(
            table_wrap,
            columns=episode_columns,
            show="headings",
            height=8,
            selectmode="browse",
        )
        self.deep_episode_table.heading("title", text="主题")
        self.deep_episode_table.heading("status", text="状态")
        self.deep_episode_table.heading("question", text="调研问题")
        self.deep_episode_table.heading("updated", text="更新时间")
        self.deep_episode_table.column("title", width=180, anchor="w")
        self.deep_episode_table.column("status", width=80, anchor="center")
        self.deep_episode_table.column("question", width=360, anchor="w")
        self.deep_episode_table.column("updated", width=150, anchor="center")
        episode_scroll = ttk.Scrollbar(table_wrap, orient="vertical", command=self.deep_episode_table.yview)
        self.deep_episode_table.configure(yscrollcommand=episode_scroll.set)
        self.deep_episode_table.pack(side="left", fill="both", expand=True)
        episode_scroll.pack(side="right", fill="y")
        self.deep_episode_table.bind("<<TreeviewSelect>>", self.on_deep_episode_select)

        episode_actions = tk.Frame(episode_section, bg=CARD_COLOR)
        episode_actions.pack(fill="x", pady=(10, 0))
        self.create_action_button(episode_actions, "新增主题", self.new_deep_episode_popup, SOFT_BLUE, PRIMARY_COLOR)
        self.create_action_button(episode_actions, "编辑主题", self.edit_deep_episode_popup, CARD_COLOR, PRIMARY_COLOR)
        self.create_action_button(episode_actions, "删除主题", self.delete_deep_episode, "#FFECEC", "#D70015")
        self.create_action_button(episode_actions, "看调研", self.show_deep_research, CARD_COLOR, PRIMARY_COLOR)
        self.create_action_button(episode_actions, "看审稿", self.show_deep_audit, CARD_COLOR, PRIMARY_COLOR)
        self.create_action_button(episode_actions, "看写稿意见", self.show_deep_script_notes, CARD_COLOR, PRIMARY_COLOR)
        self.create_action_button(episode_actions, "看脚本", self.show_deep_script, CARD_COLOR, PRIMARY_COLOR)
        self.create_action_button(episode_actions, "看日志", self.show_deep_agent_log, CARD_COLOR, PRIMARY_COLOR)

        run_actions = tk.Frame(inner, bg=CARD_COLOR)
        run_actions.pack(fill="x", pady=(14, 0))
        self.deep_run_button = self.create_action_button(
            run_actions,
            "调研并写稿",
            self.start_deep_run,
            "#111111",
            "white",
        )
        self.deep_run_series_button = self.create_action_button(
            run_actions,
            "整组调研写稿",
            self.start_deep_series_run,
            "#2C2C2E",
            "white",
        )
        self.deep_generate_video_button = self.create_action_button(
            run_actions,
            "审核后生成视频",
            self.start_deep_generate_video,
            PRIMARY_COLOR,
            "white",
        )
        self.refresh_deep_lists()

    def create_action_button(self, parent, text, command, bg, fg):
        button = tk.Button(
            parent,
            text=text,
            command=command,
            bg=bg,
            fg=fg,
            activebackground=bg,
            activeforeground=fg,
            relief="flat",
            borderwidth=0,
            font=("Microsoft YaHei UI", 9, "bold"),
            padx=12,
            pady=8,
            cursor="hand2",
        )
        button.pack(side="left", padx=(0, 8), pady=(0, 4))
        return button

    def get_episode_status(self, episode):
        return self.get_deep_episode_status(episode)

    def get_deep_episode_status(self, episode):
        if episode.get("generated") and episode.get("video_path") and episode.get("published"):
            return "已发布"
        if episode.get("generated") and episode.get("video_path"):
            return "待发布"
        if episode.get("review_ready") and episode.get("script_path"):
            return "待生成视频"
        return "未生成"

    def refresh_deep_lists(self):
        if not hasattr(self, "deep_series_table"):
            return
        self.deep_series_row_map = {}
        self.deep_episode_row_map = {}
        self.deep_series_table.delete(*self.deep_series_table.get_children())
        self.deep_episode_table.delete(*self.deep_episode_table.get_children())

        for series_index, series in enumerate(self.deep_config.get("series", [])):
            row_id = f"s{series_index}"
            self.deep_series_row_map[row_id] = series_index
            self.deep_series_table.insert(
                "",
                "end",
                iid=row_id,
                values=(
                    series.get("title", "未命名系列"),
                    len(series.get("episodes", [])),
                    series.get("description", ""),
                ),
            )
        children = self.deep_series_table.get_children()
        if children:
            self.deep_series_table.selection_set(children[0])
            self.deep_series_table.focus(children[0])
            self.on_deep_series_select()

    def refresh_deep_episode_table(self, series_index):
        self.deep_episode_row_map = {}
        self.deep_episode_table.delete(*self.deep_episode_table.get_children())
        if series_index < 0:
            return
        series_list = self.deep_config.get("series", [])
        if series_index >= len(series_list):
            return
        for episode_index, episode in enumerate(series_list[series_index].get("episodes", [])):
            row_id = f"e{series_index}_{episode_index}"
            self.deep_episode_row_map[row_id] = (series_index, episode_index)
            self.deep_episode_table.insert(
                "",
                "end",
                iid=row_id,
                values=(
                    episode.get("title", "未命名主题"),
                    self.get_episode_status(episode),
                    episode.get("question", ""),
                    episode.get("generated_at", ""),
                ),
            )
        children = self.deep_episode_table.get_children()
        if children:
            self.deep_episode_table.selection_set(children[0])
            self.deep_episode_table.focus(children[0])
            self.on_deep_episode_select()
        else:
            self.deep_episode_title_var.set("")
            self.deep_episode_question_var.set("")

    def get_selected_deep_series_index(self):
        if hasattr(self, "deep_series_table"):
            episode_selection = self.deep_episode_table.selection()
            if episode_selection:
                return self.deep_episode_row_map.get(episode_selection[0], (-1, -1))[0]
            series_selection = self.deep_series_table.selection()
            if series_selection:
                return self.deep_series_row_map.get(series_selection[0], -1)
            return -1
        selection = self.deep_series_list.curselection()
        return selection[0] if selection else -1

    def get_selected_deep_episode_index(self):
        if hasattr(self, "deep_episode_table"):
            selection = self.deep_episode_table.selection()
            if not selection:
                return -1
            return self.deep_episode_row_map.get(selection[0], (-1, -1))[1]
        selection = self.deep_episode_list.curselection()
        return selection[0] if selection else -1

    def on_deep_series_select(self, _event=None):
        series_index = -1
        if hasattr(self, "deep_series_table"):
            selection = self.deep_series_table.selection()
            if selection:
                series_index = self.deep_series_row_map.get(selection[0], -1)
            if series_index < 0:
                return
            series = self.deep_config.get("series", [])[series_index]
            self.deep_series_title_var.set(series.get("title", ""))
            self.deep_series_desc_var.set(series.get("description", ""))
            self.refresh_deep_episode_table(series_index)
            self.refresh_deep_publish_list()
            return
        index = self.get_selected_deep_series_index()
        if index < 0:
            return

    def on_deep_episode_select(self, _event=None):
        series, episode = self.get_selected_deep_target()
        if not series or not episode:
            return
        self.deep_episode_title_var.set(episode.get("title", ""))
        self.deep_episode_question_var.set(episode.get("question", ""))
        self.refresh_deep_publish_list()

    def new_deep_series_popup(self):
        data = self.ask_series_dialog("新增系列", "", "")
        if not data:
            return
        self.deep_config.setdefault("series", []).append({
            "title": data["title"],
            "description": data["description"],
            "episodes": [],
        })
        deep_series.save_config(self.deep_config)
        self.refresh_deep_lists()
        self.append_log("深度系列已新增。\n")

    def edit_deep_series_popup(self):
        index = self.get_selected_deep_series_index()
        if index < 0:
            self.append_log("请先选择一个深度系列。\n")
            return
        series = self.deep_config.get("series", [])[index]
        data = self.ask_series_dialog("编辑系列", series.get("title", ""), series.get("description", ""))
        if not data:
            return
        series["title"] = data["title"]
        series["description"] = data["description"]
        series.setdefault("episodes", [])
        deep_series.save_config(self.deep_config)
        self.refresh_deep_lists()
        self.append_log("深度系列已更新。\n")

    def new_deep_episode_popup(self):
        series_index = self.get_selected_deep_series_index()
        if series_index < 0:
            self.append_log("请先选择一个深度系列。\n")
            return
        data = self.ask_episode_dialog("新增主题", "", "")
        if not data:
            return
        self.deep_config["series"][series_index].setdefault("episodes", []).append({
            "title": data["title"],
            "question": data["question"],
        })
        deep_series.save_config(self.deep_config)
        self.refresh_deep_lists()
        self.append_log("深度主题已新增。\n")

    def edit_deep_episode_popup(self):
        series_index = self.get_selected_deep_series_index()
        episode_index = self.get_selected_deep_episode_index()
        if series_index < 0 or episode_index < 0:
            self.append_log("请先选择一个主题。\n")
            return
        episode = self.deep_config["series"][series_index].get("episodes", [])[episode_index]
        data = self.ask_episode_dialog(
            "编辑主题",
            episode.get("title", ""),
            episode.get("question", episode.get("title", "")),
        )
        if not data:
            return
        episode["title"] = data["title"]
        episode["question"] = data["question"]
        deep_series.save_config(self.deep_config)
        self.refresh_deep_lists()
        self.append_log("深度主题已更新。\n")

    def delete_deep_series(self):
        index = self.get_selected_deep_series_index()
        if index < 0:
            self.append_log("请先选择一个深度系列。\n")
            return
        series = self.deep_config.get("series", [])[index]
        if not messagebox.askyesno("删除系列", f"确认删除系列：{series.get('title', '')}？", parent=self.root):
            return
        del self.deep_config["series"][index]
        deep_series.save_config(self.deep_config)
        self.refresh_deep_lists()
        self.append_log("深度系列已删除。\n")

    def delete_deep_episode(self):
        series_index = self.get_selected_deep_series_index()
        episode_index = self.get_selected_deep_episode_index()
        if series_index < 0 or episode_index < 0:
            self.append_log("请先选择一个主题。\n")
            return
        episode = self.deep_config["series"][series_index].get("episodes", [])[episode_index]
        if not messagebox.askyesno("删除主题", f"确认删除主题：{episode.get('title', '')}？", parent=self.root):
            return
        del self.deep_config["series"][series_index]["episodes"][episode_index]
        deep_series.save_config(self.deep_config)
        self.refresh_deep_lists()
        self.append_log("深度主题已删除。\n")

    def ask_series_dialog(self, title, init_title, init_desc):
        dialog = tk.Toplevel(self.root)
        dialog.title(title)
        dialog.configure(bg=BG_COLOR)
        dialog.transient(self.root)
        dialog.grab_set()
        dialog.geometry("520x260")
        title_var = tk.StringVar(value=init_title)
        desc_var = tk.StringVar(value=init_desc)
        result = {}
        self.build_dialog_entry(dialog, "系列名称", title_var)
        self.build_dialog_entry(dialog, "系列说明", desc_var)
        self.build_dialog_buttons(dialog, result, {"title": title_var, "description": desc_var})
        self.root.wait_window(dialog)
        return result or None

    def ask_episode_dialog(self, title, init_title, init_question):
        dialog = tk.Toplevel(self.root)
        dialog.title(title)
        dialog.configure(bg=BG_COLOR)
        dialog.transient(self.root)
        dialog.grab_set()
        dialog.geometry("560x260")
        title_var = tk.StringVar(value=init_title)
        question_var = tk.StringVar(value=init_question)
        result = {}
        self.build_dialog_entry(dialog, "主题名称", title_var)
        self.build_dialog_entry(dialog, "调研问题", question_var)
        self.build_dialog_buttons(dialog, result, {"title": title_var, "question": question_var})
        self.root.wait_window(dialog)
        return result or None

    def build_dialog_entry(self, dialog, label, text_var):
        row = tk.Frame(dialog, bg=BG_COLOR)
        row.pack(fill="x", padx=22, pady=(18, 0))
        tk.Label(row, text=label, bg=BG_COLOR, fg=TEXT_COLOR, font=("Microsoft YaHei UI", 10, "bold")).pack(anchor="w")
        tk.Entry(
            row,
            textvariable=text_var,
            bg=CARD_COLOR,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground=BORDER_COLOR,
            font=("Microsoft YaHei UI", 10),
        ).pack(fill="x", pady=(8, 0), ipady=8)

    def build_dialog_buttons(self, dialog, result, fields):
        row = tk.Frame(dialog, bg=BG_COLOR)
        row.pack(fill="x", padx=22, pady=(22, 0))

        def save():
            title_value = fields["title"].get().strip()
            if not title_value:
                messagebox.showwarning("提示", "标题不能为空", parent=dialog)
                return
            for key, var in fields.items():
                result[key] = var.get().strip()
            if "question" in result and not result["question"]:
                result["question"] = result["title"]
            dialog.destroy()

        tk.Button(row, text="取消", command=dialog.destroy, bg=CARD_COLOR, fg=TEXT_COLOR, relief="flat", padx=18, pady=9).pack(side="right")
        tk.Button(row, text="保存", command=save, bg=PRIMARY_COLOR, fg="white", relief="flat", padx=18, pady=9).pack(side="right", padx=(0, 10))

    def get_selected_deep_target(self):
        series_index = self.get_selected_deep_series_index()
        episode_index = self.get_selected_deep_episode_index()
        if series_index < 0 or episode_index < 0:
            return None, None
        series = self.deep_config["series"][series_index]
        episode = series.get("episodes", [])[episode_index]
        return series, episode

    def show_deep_research(self):
        self.show_deep_file("调研详细内容", "research_path")

    def show_deep_audit(self):
        self.show_deep_file("审稿详细意见", "audit_path")

    def show_deep_script(self):
        self.show_deep_file("最终脚本", "script_path")

    def show_deep_script_notes(self):
        self.show_deep_file("写稿详细意见", "script_notes_path")

    def show_deep_agent_log(self):
        self.show_deep_file("多智能体交互日志", "agent_log_path")

    def show_deep_file(self, title, key):
        _series, episode = self.get_selected_deep_target()
        if not episode:
            self.append_log("请先选择一个主题。\n")
            return
        path = episode.get(key, "")
        if not path or not os.path.exists(path):
            self.append_log(f"文件不存在：{path}\n")
            return
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        self.show_text_dialog(title, content, path)

    def show_text_dialog(self, title, content, path):
        dialog = tk.Toplevel(self.root)
        dialog.title(title)
        dialog.configure(bg=BG_COLOR)
        dialog.transient(self.root)
        dialog.geometry("900x680")
        top = tk.Frame(dialog, bg=BG_COLOR)
        top.pack(fill="x", padx=18, pady=(16, 8))
        tk.Label(top, text=title, bg=BG_COLOR, fg=TEXT_COLOR, font=("Microsoft YaHei UI", 14, "bold")).pack(side="left")
        tk.Button(top, text="打开文件", command=lambda: os.startfile(path), bg=SOFT_BLUE, fg=PRIMARY_COLOR, relief="flat", padx=14, pady=8).pack(side="right")
        text = scrolledtext.ScrolledText(
            dialog,
            bg=LOG_BG,
            fg=TEXT_COLOR,
            relief="flat",
            highlightthickness=1,
            highlightbackground=BORDER_COLOR,
            font=("Microsoft YaHei UI", 10),
            wrap="word",
            padx=14,
            pady=14,
        )
        text.pack(fill="both", expand=True, padx=18, pady=(0, 18))
        text.insert("1.0", content)
        text.configure(state="disabled")

    def open_latest_dir(self):
        for key in ("video_path", "audio_path", "brief_path", "script_path", "research_path"):
            path = self.latest_result.get(key)
            if path and os.path.exists(path):
                os.startfile(os.path.dirname(path))
                return

        today = datetime.date.today().strftime("%Y-%m-%d")
        fallback_dir = os.path.join(main.ROOT_DIR, "audioContent", today)
        if os.path.exists(fallback_dir):
            os.startfile(fallback_dir)


def launch():
    root = tk.Tk()
    app = NewsBriefApp(root)
    root.mainloop()
    return app


if __name__ == "__main__":
    launch()
